[package]
name = "strategies"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-primitives = { version = "0.7" }
risc0-steel = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.0.0" }
