[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "tests"
ffi = true
# fs_permissions = [{ access = "read", path = "./script/" }]
fs_permissions = [{ access = "read", path = "./" }]

solc = "0.8.17"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
